# Generated by Django 4.2.4 on 2023-08-25 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_room_participants"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
